/**
 * Builds the GitHub issue title + body from a normalized request.
 *
 * The body is the prompt the selected coding agent will read once approved, so it
 * must include all constraints, allowed paths, and attachment links.
 */

import type { ChangeRequest, EmailAttachment, InboundEmail, Site, SiteRepo } from '../types';

export interface PresignedAttachment {
  filename: string;
  mime_type: string | null;
  size_bytes: number | null;
  url: string;
}

export interface BuildIssueArgs {
  request_id: string;
  email: InboundEmail;
  change: ChangeRequest;
  site: Site;
  repo: SiteRepo;
  attachments: PresignedAttachment[];
}

export function buildIssueTitle(change: ChangeRequest, site: Site): string {
  return `[client-request] ${site.slug}: ${truncate(change.summary, 80)}`;
}

export function buildIssueBody(args: BuildIssueArgs): string {
  const { request_id, email, change, site, repo, attachments } = args;
  const allowedGlobs = repo.allowed_globs.length > 0
    ? repo.allowed_globs.map((g) => `\`${g}\``).join(', ')
    : '_(none configured - see CLAUDE.md / AGENTS.md in this repo for the editable areas)_';

  const attachmentLines = attachments.length === 0
    ? '_(no attachments)_'
    : attachments
        .map((a) => `- [${a.filename}](${a.url}) — ${a.mime_type ?? 'application/octet-stream'} (${formatBytes(a.size_bytes)})`)
        .join('\n');

  const quotedBody = (email.text_body ?? '(no plain-text body)')
    .split('\n')
    .map((l) => `> ${l}`)
    .join('\n');

  return `# Website change request

**Internal request ID:** \`${request_id}\`
**Original sender:** ${email.from_addr}
**Received:** ${new Date(email.received_at).toISOString()}
**Site:** ${site.name} (\`${site.slug}\`)
**Edit type:** \`${change.edit_type}\`

## Requested change (summary)

${change.summary}

## Original email

${quotedBody}

## Normalized request

\`\`\`json
${prettyJson(change.payload_json)}
\`\`\`

## Attachments

${attachmentLines}

> Attachment URLs are presigned and expire. If your run needs them, fetch
> them at the start of your task and commit them to the repo (see allowed paths).

## Allowed file paths for this change

${allowedGlobs}

## Constraints for the agent

- Make the **minimal possible diff**. One PR, one logical change.
- Edit content files (\`src/content/**\`, \`src/data/**\`, \`public/images/**\`, etc.) only. Do not modify Vue components unless strictly required to wire a new content key.
- Do **not** edit: \`package.json\`, lockfiles, \`.github/**\`, \`wrangler.*\`, \`.env*\`, \`vite.config.*\`, \`public/_redirects\`, or any CI / deployment config.
- Do **not** add or upgrade dependencies.
- Open one PR against \`main\`. Title: \`[client-request] <summary>\`. Body must include \`Closes #<this issue>\`.
- If the request is ambiguous, comment on this issue asking for clarification instead of guessing.

## Approval

Add exactly one of these labels to start an agent:

- **\`approve-for-claude\`** - run Claude Code Action
- **\`approve-for-codex\`** - run OpenAI Codex Action

Add **\`rejected\`** to discard.

---

<sub>Generated by patchline-worker. ${new Date().toISOString()}</sub>
`;
}

// ---------------------------------------------------------------------------

function truncate(s: string, n: number): string {
  return s.length <= n ? s : s.slice(0, n - 1) + '…';
}

function formatBytes(n: number | null): string {
  if (n == null) return 'unknown size';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(2)} MB`;
}

function prettyJson(s: string): string {
  try { return JSON.stringify(JSON.parse(s), null, 2); }
  catch { return s; }
}
